=== hophuoc1403/XML-and-DTD-oke/student-valid.dtd
<!ELEMENT houses (house*)>
<!ELEMENT house (room+)>
<!ELEMENT room (dimensions,windows,furniture*)>
<!ELEMENT dimensions (width,length)>
<!ELEMENT windows (window*)>
<!ELEMENT window (elevation,width,height)>
<!ELEMENT furniture (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT length EMPTY>
<!ELEMENT elevation (#PCDATA)>

=== hophuoc1403/XML-and-DTD-oke/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE houses SYSTEM "student-valid.dtd" [

]>
<houses>
    <house>
        <room>
            <dimensions>
                <width></width>
                <length />
            </dimensions>
            <windows>
                <window>
                    <elevation></elevation>
                    <width></width>
                    <height></height>
                </window>
            </windows>
            <furniture></furniture>
            
        </room>
    </house>
</houses>
